#include <iostream>
#include <fstream>
using namespace std;
int main() {
	int choix ;
    std::fstream fichier("emploi du tempsGIS2.pdf", std::ios::out | std::ios::binary);
    cout<<"pour affiches les professeurs seulement tapez: 1"<<endl ;
    cout<<"pour affiches les salles seulement tapez     : 2"<<endl ;
    cout<<"pour affiches les matires seulement tapez    : 3"<<endl ;
    cout<<"pour quiter tapez                            : 0"<<endl ;
    cin>>choix ;
    switch(choix)
    	{
    		case 1:
    				{
				     fichier << "%PDF-1.5\n%\xE2\xE3\xCF\xD3\n";

    // Catalogue PDF
    fichier << "1 0 obj\n"
            << "<<\n"
            << "  /Type /Catalog\n"
            << "  /Pages 2 0 R\n"
            << ">>\n"
            << "endobj\n";

    // Page PDF
    fichier << "2 0 obj\n"
            << "<<\n"
            << "  /Type /Page\n"
            << "  /MediaBox [0 0 612 792]\n"
            << "  /Parent 1 0 R\n"
            << "  /Contents 3 0 R\n"
            << ">>\n"
            << "endobj\n";

    // Contenu PDF
    fichier << "3 0 obj\n"
            << "<<\n"
            << "  /Length 80\n"
            << ">>\n"
            << "stream\n"
            << "BT\n"
            << "  /F1 24 Tf\n"
            << "  100 730 Td\n"
            << "  (Emploi du temps GI S2 :) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 680 Td\n"
            << "  (Lundi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 650 Td\n"
            << "  (8h - 10h: Mr:TOUMI) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: Mr:Baddi)  Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: Mr: TOUMI ::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h: Mr: TOUMI::G1) Tj\n"   
            <<"j"
			<<"0 -20 Td\n"         
            << "ET\n"
            << "BT\n"
            << "  /F1 19 Tf\n"
            << "  100 560 Td\n" //L'EMPLACEMENT
            << "  (Mardi ) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 540 Td\n"
            << "  (8h - 10h: Mr:Aroussi) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: Mr:arroussi::G2  Mme:Ghoubari ::G1) Tj\n"
            <<"0 -20 Td\n"
            <<"  (14h - 16h: Mr:arroussi::G1 Mme:Ghoubari ::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h: Mme:Ghoubari) Tj\n"           
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 450 Td\n"
            << "  (Mercredi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 430 Td\n"
            << "  (8h - 10h: Mr:chrkaoui ) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: Mr:chrkaou::G1/Mme:Moukhlis::G2/Mr:Regragui ::G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: Mme:Moukhlis::G1/Mr:Regragui  ::G2/Mr:chrkaou::G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:TP:Mr:Regragui  ::G1/Mr:chrkaou::G2/Mme:Moukhlis::G3  ) Tj\n"
            << "BT\n"
           << "ET\n"
           << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 340 Td\n"
            << "  (jeudi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 310 Td\n"
            << "  (8h - 10h: Mr:Taki) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: Mr: saidi) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: Mr:Taki G1/Mr: saidi G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h: Mr: saidi G1/Mr:Taki ) Tj\n"
            << "BT\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 230 Td\n"
            << "  (vendredi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 210 Td\n"
            << "  (8h - 10h:Mme:Moukhlis) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: Mr:Mabrouk) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h:  Mr:Mabrouk ::G1 /Mme:Moukhlis::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:  Mr:Mabrouk::G2 /Mme:Moukhlis::G1) Tj\n"           
            << "BT\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 120 Td\n"
            << "  (samedi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 100 Td\n"
            << "  (8h - 10h:TP : Mr:Regragui G1 / Mr:Mabrouk :: G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: tp:Mr:Mabrouk :: G2/ Mr:Regragui G1 ) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: tp:Mr:Mabrouk :: G1/ Mr:Regragui G2) Tj\n"            
            << "BT\n"
           << "ET\n"
           << "endstream\n"
           << "endobj\n";
           fichier << "ET\n"
          << "endstream\n"
          << "endobj\n";

fichier << "xref\n"
        << "0 4\n"
        << "0000000000 65535 f \n"
        << "0000000017 00000 n \n"
        << "0000000078 00000 n \n"
        << "0000000123 00000 n \n"
        << "trailer\n"
        << "<<\n"
        << "  /Size 4\n"
        << "  /Root 1 0 R\n"
        << ">>\n"
        << "startxref\n"
        << "242\n"
        << "%%EOF\n";

fichier.close();
      cout<<"Vous trouverez le PDF dans votre document ";
       break ;
		}
	
	case 2:
		{
			    fichier << "%PDF-1.5\n%\xE2\xE3\xCF\xD3\n";

    // Catalogue PDF
    fichier << "1 0 obj\n"
            << "<<\n"
            << "  /Type /Catalog\n"
            << "  /Pages 2 0 R\n"
            << ">>\n"
            << "endobj\n";

    // Page PDF
    fichier << "2 0 obj\n"
            << "<<\n"
            << "  /Type /Page\n"
            << "  /MediaBox [0 0 612 792]\n"
            << "  /Parent 1 0 R\n"
            << "  /Contents 3 0 R\n"
            << ">>\n"
            << "endobj\n";

    // Contenu PDF
    fichier << "3 0 obj\n"
            << "<<\n"
            << "  /Length 80\n"
            << ">>\n"
            << "stream\n"
            << "BT\n"
            << "  /F1 24 Tf\n"
            << "  100 730 Td\n"
            << "  (Emploi du temps GI S2 :) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 680 Td\n"
            << "  (Lundi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 650 Td\n"
            << "  (8h - 10h:  salle cours:3 etage:1) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: salle cours:3 etage:1)  Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: salle td:2 etage :3 ::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:salle td:2 etage :3::G1) Tj\n"   
            <<"j"
			<<"0 -20 Td\n"         
            << "ET\n"
            << "BT\n"
            << "  /F1 19 Tf\n"
            << "  100 560 Td\n" //L'EMPLACEMENT
            << "  (Mardi ) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 540 Td\n"
            << "  (8h - 10h:  salle cours:3 etage:1) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h:salle td:2 etage :3 ::G2 /salle td:1 etage:3 ::G1) Tj\n"
            <<"0 -20 Td\n"
            <<"  (14h - 16h: salle td:2 etage :3::G1/ salle td:1 etage:3 ::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h: salle cours:3 etage:1) Tj\n"           
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 450 Td\n"
          << "  (Mercredi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 430 Td\n"
            << "  (8h - 10h: salle cours:3 etage:1) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: tpsalle de tp:2 etage3::G1/salle de tp:2 etage3::G2/salle de tp:3 etage3 ::G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: TPsalle de tp:2 etage3::G1/salle de tp:3 etage3 ::G2/salle de tp:2 etage3::G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:TP:salle de tp:3 etage3 ::G1/salle de tp:2 etage3::G2/salle de tp:2 etage3::G3  ) Tj\n"
            << "BT\n"
           << "ET\n"
           << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 340 Td\n"
            << "  (jeudi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 310 Td\n"
            << "  (8h - 10h:  salle cours:3 etage:1) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h:  salle cours:3 etage:1) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h:  salle td:2 etage :3::G1/ salle td:1 etage:3 ::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:  salle td:2 etage :3::G2/ salle td:1 etage:3 ::G1 ) Tj\n"
            << "BT\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 230 Td\n"
            << "  (vendredi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 210 Td\n"
            << "  (8h - 10h:salle cours:3 etage:1) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: salle cours:3 etage:) Tj\n"
            << "  0 -20 Td\n"
              << "  (14h - 16h:  salle td:2 etage :3::G1/ salle td:1 etage:3 ::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:  salle td:2 etage :3::G2/ salle td:1 etage:3 ::G1 ) Tj\n"
            << "BT\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 120 Td\n"
            << "  (samedi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 100 Td\n"
            << "  (10h - 12h: tpsalle de tp:2 etage3::G1/salle de tp:3etage3::G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: TPsalle de tp:2 etage3::G3/salle de tp:3 etage3 ::G2/) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:TP:salle de tp:3 etage3 ::G1/salle de tp:2 etage3::G2/ ) Tj\n"         
            << "BT\n"
           << "ET\n"
           << "endstream\n"
           << "endobj\n";
           fichier << "ET\n"
          << "endstream\n"
          << "endobj\n";

fichier << "xref\n"
        << "0 4\n"
        << "0000000000 65535 f \n"
        << "0000000017 00000 n \n"
        << "0000000078 00000 n \n"
        << "0000000123 00000 n \n"
        << "trailer\n"
        << "<<\n"
        << "  /Size 4\n"
        << "  /Root 1 0 R\n"
        << ">>\n"
        << "startxref\n"
        << "242\n"
        << "%%EOF\n";

fichier.close();
      cout<<"Vous trouverez le PDF dans votre document ";
      break ;
		}
		case 3:
			{
				    fichier << "%PDF-1.5\n%\xE2\xE3\xCF\xD3\n";

    // Catalogue PDF
    fichier << "1 0 obj\n"
            << "<<\n"
            << "  /Type /Catalog\n"
            << "  /Pages 2 0 R\n"
            << ">>\n"
            << "endobj\n";

    // Page PDF
    fichier << "2 0 obj\n"
            << "<<\n"
            << "  /Type /Page\n"
            << "  /MediaBox [0 0 612 792]\n"
            << "  /Parent 1 0 R\n"
            << "  /Contents 3 0 R\n"
            << ">>\n"
            << "endobj\n";

    // Contenu PDF
    fichier << "3 0 obj\n"
            << "<<\n"
            << "  /Length 80\n"
            << ">>\n"
            << "stream\n"
            << "BT\n"
            << "  /F1 24 Tf\n"
            << "  100 730 Td\n"
            << "  (Emploi du temps GI S2 :) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 680 Td\n"
            << "  (Lundi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 650 Td\n"
            << "  (8h - 10h: cours:systeme d'exploitation) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: cours:poo c++)  Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: td:systeme d'exploitation ::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:td:systeme d'exploitation ::G1) Tj\n"   
            <<"j"
			<<"0 -20 Td\n"         
            << "ET\n"
            << "BT\n"
            << "  /F1 19 Tf\n"
            << "  100 560 Td\n" //L'EMPLACEMENT
            << "  (Mardi ) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 540 Td\n"
            << "  (8h - 10h: cours:base de donneés) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: td:bdd::G2 td:algebreG1) Tj\n"
            <<"0 -20 Td\n"
            <<"  (14h - 16h: td:bdd::G2 td:algebreG1) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h: cours:algebre) Tj\n"           
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 450 Td\n"
            << "  (Mercredi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 430 Td\n"
            << "  (8h - 10h: COURS :vb.net) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: salle de tp1 etage 3::G1/ salle de tp2 etage 3::G2/ salle de tp3 etage 3 ::G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: salle de tp2 etage 3::G1/systeme d'exploitation ::G2/salle de tp3 etage: 3::G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:salle de tp3 etage 3::G1/salle cours:3 etage:1::G2/salle de tp2 etage 3::G3  ) Tj\n"
            << "BT\n"
           << "ET\n"
           << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 340 Td\n"
            << "  (jeudi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 310 Td\n"
            << "  (8h - 10h: cours:: analyse) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: cours::structure de donneés) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: TD: analyse G1/structure G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h: TD:structure G1/analyse G2 ) Tj\n"
            << "BT\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 230 Td\n"
            << "  (vendredi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 210 Td\n"
            << "  (8h - 10h:COURS:MERISE) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: cours : reseau informatique) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h:  td:reseau informatique ::G1 /merise::G2) Tj\n"
            << "  0 -20 Td\n"
            << "  (16h - 18h:  td:reseau informatique ::G2 /merise::G1) Tj\n"           
            << "BT\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 18 Tf\n"
            << "  100 120 Td\n"
            << "  (samedi) Tj\n"
            << "ET\n"
            << "BT\n"
            << "  /F1 12 Tf\n"
            << "  100 100 Td\n"
            << "  (8h - 10h:TP : base de données G1 / reseau informatique G3) Tj\n"
            << "  0 -20 Td\n"
            << "  (10h - 12h: tp:reseau informatique G2/base de données G1 ) Tj\n"
            << "  0 -20 Td\n"
            << "  (14h - 16h: tp:reseau informatique G1/base de données G2) Tj\n"            
            << "BT\n"
           << "ET\n"
           << "endstream\n"
           << "endobj\n";
           fichier << "ET\n"
          << "endstream\n"
          << "endobj\n";

fichier << "xref\n"
        << "0 4\n"
        << "0000000000 65535 f \n"
        << "0000000017 00000 n \n"
        << "0000000078 00000 n \n"
        << "0000000123 00000 n \n"
        << "trailer\n"
        << "<<\n"
        << "  /Size 4\n"
        << "  /Root 1 0 R\n"
        << ">>\n"
        << "startxref\n"
        << "242\n"
        << "%%EOF\n";

fichier.close();
      cout<<"Vous trouverez le PDF dans votre document ";
      break ;
			}
			case 4:
				cout<<"au revoir" ;
				break;
			default:
			    cout<<"le choix inccorect" ;
				break;	

}
return 0;
}


